### ISSUE TITLE
Missing hint when ready-flag is not set

### ISSUE THREAD

**Issue by Angbunna** [TechnoX/rcj-rescue-scoring#40] opened 2017-07-13 23:56 UTC
I tried to add a run with a map that is not marked as ready – it does nothing (pretends to load) and prints no error message to give a clue on what's the problem :(

![image](https://user-images.githubusercontent.com/29250362/28192569-58a95a34-6837-11e7-9216-c1c25dfb9425.png)

**Comment by janblumenkamp** [comment] 2017-07-14 05:41
I created an issue for this in the first place, but we closed it as it was not a bug. I commented later though that a hint like a popup about was is wrong would be helpful as well.
[https://github.com/TechnoX/rcj-rescue-scoring/issues/31](url)

**Closed** 2017-07-14 09:58 UTC
