### ISSUE TITLE
Design breaks after incrementing number of dead victims

### ISSUE THREAD

**Issue by Angbunna** [TechnoX/rcj-rescue-scoring#41] opened 2017-07-14 00:06 UTC
It looks like this:

![image](https://user-images.githubusercontent.com/29250362/28192800-c2de7424-6838-11e7-9eab-42f05bb45753.png)

but after decrementing the number of victims the number is displayed correctly again. The problem only occurs at dead victims, live victims work perfectly.

**Comment by TechnoX** [comment] 2017-07-14 10:02
Can't reproduce :( 

Is this happening on all maps or just certain? Can I get more data on when it happened? Before or after pressing anything on the map?

**Comment by rrrobo** [comment] 2017-07-14 14:04
fixed with 19f54ef

**Comment by TechnoX** [comment] 2017-07-15 09:36
Working again according to Jennifer

**Closed by TechnoX** 2017-07-15 09:36 UTC
